# Generated by Django 2.0 on 2019-09-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={'ordering': ['-c_time'], 'verbose_name': 'code', 'verbose_name_plural': 'code'},
        ),
    ]
